# Generated by Django 5.1.6 on 2025-03-20 10:26

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(validators=[stories.models.validate_story_length]),
        ),
    ]
